### PR TITLE
spelling fix

### PR DESCRIPTION
**Pull request by mjosephmiller**

### CODE REVIEW

**Comment by andreruffert** [comment]
@mjosephmiller thanks! ✌️

**Comment by mjosephmiller** [comment]
Will try a make a better contribution next time...how about making a Munich map?! [bitmoji](https://render.bitstrips.com/v2/cpanel/7548831-212220389_1-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by mjosephmiller** [comment]
Will try a make a better contribution next time...how about making a Munich map?! bitmoji

**Comment by andreruffert** [comment]
So far there is only a static one  http://blog.honeypot.io/munich-tech-map/
but it's definitely an option to have a interactive munich tech map in the future.

**Pull request merged**
